version: '3.9'
services:
  postgres:
    container_name: postgres_veterans
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5050:5432'
    volumes:
      # This volume saves the data in the host machine
      - postgres_data:/var/lib/postgresql/data
  server:
    build: ./server
    container_name: server_veterans
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  react:
    build: ./client
    container_name: react_veterans
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data:
