export const paths = {
  home: '/',
  genericSeason: '/temporades/2017-2018',
  season: '/temporades/:currentSeason',
  book: '/llibre-veterans-hoquei-patins-fcb',
  login: '/admin/login',
  register: '/admin/register',
  verify: '/admin/verify',
  me: '/admin/me',
  newChapter: '/admin/new-chapter',
  userChapterList: '/admin/llistat-temporades',
  editChapter: '/admin/temporades/edit-chapter/:currentSeason',
  blog: '/blog',
  players: '/jugadors',
};
