version: '3.9'
services:
  postgres:
    container_name: postgres_veterans
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5050:5432'
    volumes:
      # This volume saves the data in the host machine
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
