version: '3.9'
services:
  postgres:
    container_name: postgres_veterans
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5050:5432'
    # volumes:
    # This volume saves the data in the host machine
    # - data:/var/lib/postgresql/data
# volumes:
# data:
